package com.razkuuuuuuu.touragency.web.controller.commands.get.base;

public enum LoadCommandName {
    CATALOG_LOAD_COMMAND,
    SIGN_IN_LOAD_COMMAND,
    SIGN_UP_LOAD_COMMAND,
    PROFILE_LOAD_COMMAND,
    TOUR_INFO_LOAD_COMMAND,
    ERROR_PAGE_LOAD_COMMAND,
    BOOK_TOUR_LOAD_COMMAND,
    USERS_LIST_LOAD_COMMAND,
    ADD_EMPLOYEE_LOAD_COMMAND,
    CUSTOMER_BOOKING_LOAD_COMMAND,
    BANNED_PAGE_LOAD_COMMAND,
    CREATE_TOUR_LOAD_COMMAND
}
